services:
  app:
    container_name: app
    restart: always
    build:
      dockerfile: ./Dockerfile
    links:
      - db
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
  db:
    image: 'postgres:latest'
    container_name: database
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 1337:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata